(function(g){var window=this;var Jia=function(a,b){return g.ac(a,b)},Kia=function(a){if(a.hc&&"function"==typeof a.hc)return a.hc();
if(g.w(a))return a.split("");if(g.Aa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Xb(a)},Lia=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Aa(a)||g.w(a))(0,g.F)(a,b,void 0);else{if(a.pd&&"function"==typeof a.pd)var c=a.pd();else if(a.hc&&"function"==typeof a.hc)c=void 0;else if(g.Aa(a)||g.w(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Yb(a);d=Kia(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},m4=function(a){g.$o(a,"zx",g.Hb());
return a},n4=function(a,b,c){g.za(c)||(c=[String(c)]);
g.fp(a.o,b,c)},o4=function(){},p4=function(a){if(!a.l&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},q4=function(a){var b;
(b=a.g)||(b={},p4(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b},r4=function(a){return(a=p4(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},s4=function(a,b){return b+" ["+a.X+" "+a.I+" "+a.getStatus()+"]"},Mia=function(a){return"content-type"==a.toLowerCase()},t4=function(a){a.g&&a.L&&(a.g.ontimeout=null);
a.F&&(g.x.clearTimeout(a.F),a.F=null)},Nia=function(a){return g.vd&&g.wc(9)&&g.va(a.timeout)&&g.t(a.ontimeout)},u4=function(a){a.T||(a.T=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},v4=function(a,b){if(a.g){t4(a);
var c=a.g,d=a.O[0]?g.wa:null;a.g=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},w4=function(a,b){a.l=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.B=b;a.A=5;u4(a);v4(a)},x4=function(a){return a.g?a.g.readyState:0},y4=function(a){if(a.l&&"undefined"!=typeof g.yW)if(a.O[1]&&4==x4(a)&&2==a.getStatus())s4(a,"Local request error detected and ignored");
else if(a.H&&4==x4(a))g.ng(a.Mr,0,a);else if(a.dispatchEvent("readystatechange"),4==x4(a)){s4(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Ig(String(a.I))[1]||null;if(!f&&g.x.self&&g.x.self.location){var k=g.x.self.location.protocol;f=k.substr(0,k.length-1)}e=!Oia.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<x4(a)?a.g.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";u4(a)}}finally{v4(a)}}},z4=function(a){g.rf.call(this);
this.headers=new g.No;this.U=a||null;this.l=!1;this.O=this.g=null;this.X=this.I="";this.A=0;this.B="";this.o=this.ba=this.H=this.T=!1;this.C=0;this.F=null;this.aa="";this.L=this.V=!1},A4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Pia=function(a,b){var c=[];
g.ql(b,function(a){try{var b=g.$q.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.Zq(b)&&c.push(a):c.push(a)},a);
return c},Qia=function(a,b){var c=Pia(a,b);
(0,g.F)(c,function(a){g.$q.prototype.remove.call(this,a)},a)},Ria=function(a,b,c,d){var e=new g.Qo(null,void 0);
a&&g.Ro(e,a);b&&g.So(e,b);c&&g.To(e,c);d&&(e.l=d);return e},B4=function(){this.g=[];
this.l=[]},C4=function(a){g.gu[a]&&(a=g.gu[a],(0,g.F)(a,function(a){g.eu[a]&&delete g.eu[a]}),a.length=0)},Sia=function(a){var b=g.du();
if(b)if(b.clear(a),a)C4(a);else for(var c in g.gu)C4(c)},Tia=function(){var a=(0,g.Uu)();
a&&Qia(a,a.g.uf(!0))},D4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.No;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Uia(this,a.capabilities||""),Via(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Uia=function(a,b){a.capabilities.clear();
(0,g.Ld)(b.split(","),g.B(Jia,Wia)).forEach(function(b){a.capabilities.add(b)})},Via=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},E4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},F4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},G4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Xia=function(a){return new E4(a)},H4=function(a){return g.za(a)?(0,g.H)(a,Xia):[]},I4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},J4=function(a){return g.za(a)?"["+(0,g.H)(a,I4).join(",")+"]":"null"},K4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Yia=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},L4=function(a,b){return g.Na(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},M4=function(a,b){return g.Na(a,function(a){return F4(a,b)})},N4=function(){var a=g.Xu("yt-remote-connected-devices")||[];
g.gb(a);return a},Zia=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},O4=function(a){g.Wu("yt-remote-connected-devices",a,86400)},Q4=function(){if(P4)return P4;
var a=g.Xu("yt-remote-device-id");a||(a=K4(),g.Wu("yt-remote-device-id",a,31536E3));for(var b=N4(),c=1,d=a;g.Sa(b,d);)c++,d=a+"#"+c;return P4=d},R4=function(){var a=N4(),b=Q4();
g.Sa(a,b);if(g.bv()){var c=a,d=g.eb(c,b,void 0);0>d&&g.bb(c,-(d+1),0,b)}a=Zia(a);if(0==a.length)try{g.$u.remove("remote_sid","/","youtube.com")}catch(e){}else try{g.av("remote_sid",a.join(","),-1)}catch(e){}},S4=function(){return g.Xu("yt-remote-session-browser-channel")},T4=function(){return g.Xu("yt-remote-local-screens")||[]},U4=function(){g.Wu("yt-remote-lounge-token-expiration",!0,86400)},$ia=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(T4(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.to)(c,function(a){return!g.Sa(b,a)})&&U4();
g.Wu("yt-remote-local-screens",a,31536E3)},aja=function(a,b){g.Wu("yt-remote-session-browser-channel",a);
g.Wu("yt-remote-session-screen-id",b);var c=N4(),d=Q4();g.Sa(c,d)||c.push(d);O4(c);R4()},V4=function(a){a||(g.Yu("yt-remote-session-screen-id"),g.Yu("yt-remote-session-video-id"));
R4();a=N4();g.Wa(a,Q4());O4(a)},X4=function(){if(!W4){var a=g.gr();
a&&(W4=new g.Uq(a))}return W4?!!W4.get("yt-remote-use-staging-server"):!1},bja=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Lb(a)},cja=function(a,b){var c=g.Dd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Yc(c,g.$d("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},dja=function(){var a=bja(),b=window.document.getElementById(a),c=b&&g.nt(b,"loaded");
c||b&&!c||(b=cja(a,function(){g.nt(b,"loaded")||(g.mt(b,"loaded","true"),g.ku(a),g.$r(g.B(Sia,a),0))}))},Y4=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},Z4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},a5=function(a){a.length?$4(a.shift(),function(){a5(a)}):b5()},eja=function(a){return"chrome-extension://"+a+c5},$4=function(a,b,c){var d=
window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},d5=function(a){return 0<=window.navigator.userAgent.indexOf(a)},b5=function(){var a=Z4();
a&&a(!1,"No cast extension found")},e5=function(){if(fja){var a=2,b=Z4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;$4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",b5,c)}},gja=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(e5(),a({command:"cast.sender.init"}))},hja=function(){e5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);a5(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+c5,"//www.gstatic.com/eureka/clank"+c5])},f5=function(a,b,c){g.I.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.zc=b;this.B=(0,g.A)(this.Bz,this);this.g=!1;this.l=0;this.o=this.za=null;this.A=[]},g5=function(){},h5=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.C=d||1;this.A=45E3;this.ea=new g.gp(this);this.l=new g.mg;this.l.setInterval(250)},j5=function(a,b,c){a.nh=1;
a.Hf=m4(b.clone());a.Ng=c;a.B=!0;i5(a,null)},k5=function(a,b,c,d,e){a.nh=1;
a.Hf=m4(b.clone());a.Ng=null;a.B=c;e&&(a.aw=!1);i5(a,d)},i5=function(a,b){a.Ch=(0,g.G)();
l5(a);a.ag=a.Hf.clone();n4(a.ag,"t",a.C);a.ij=0;a.fc=a.g.Cm(a.g.bj()?b:null);0<a.Ym&&(a.sl=new g.fm((0,g.A)(a.nx,a,a.fc),a.Ym));a.ea.fa(a.fc,"readystatechange",a.SI);var c=a.wg?g.hc(a.wg):{};a.Ng?(a.Pl="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.fc.send(a.ag,a.Pl,a.Ng,c)):(a.Pl="GET",a.aw&&!g.xd&&(c.Connection="close"),a.fc.send(a.ag,a.Pl,null,c));a.g.ce(1)},s5=function(a,b,c){for(var d=!0;!a.mg&&a.ij<c.length;){var e=ija(a,c);
if(e==m5){4==b&&(a.If=4,n5(15),d=!1);break}else if(e==o5){a.If=4;n5(16);d=!1;break}else p5(a,e)}4==b&&0==c.length&&(a.If=1,n5(17),d=!1);a.de=a.de&&d;d||(q5(a),r5(a))},ija=function(a,b){var c=a.ij,d=b.indexOf("\n",c);
if(-1==d)return m5;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return o5;d+=1;if(d+c>b.length)return m5;var e=b.substr(d,c);a.ij=d+c;return e},v5=function(a,b){a.Ch=(0,g.G)();
l5(a);var c=b?window.location.hostname:"";a.ag=a.Hf.clone();g.$o(a.ag,"DOMAIN",c);g.$o(a.ag,"t",a.C);try{a.ee=new window.ActiveXObject("htmlfile")}catch(n){q5(a);a.If=7;n5(22);r5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in t5)k=t5[l];else if(l in u5)k=t5[l]=u5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
t5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Zc(g.Cc("b/12014412"),d);a.ee.open();a.ee.write(g.Rc(c));a.ee.close();a.ee.parentWindow.m=(0,g.A)(a.jI,a);a.ee.parentWindow.d=(0,g.A)(a.qv,a,!0);a.ee.parentWindow.rpcClose=(0,g.A)(a.qv,a,!1);c=a.ee.createElement("DIV");a.ee.parentWindow.document.body.appendChild(c);d=g.Nc(a.ag.toString());d=g.Bb(g.Kc(d));d=g.Zc(g.Cc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Rc(d);a.g.ce(1)},l5=function(a){a.Mp=
(0,g.G)()+a.A;
w5(a,a.A)},w5=function(a,b){if(null!=a.Ph)throw Error("WatchDog timer not null");
a.Ph=x5((0,g.A)(a.uI,a),b)},y5=function(a){a.Ph&&(g.x.clearTimeout(a.Ph),a.Ph=null)},r5=function(a){a.g.Kr()||a.mg||a.g.dl(a)},q5=function(a){y5(a);
g.Le(a.sl);a.sl=null;a.l.stop();g.ip(a.ea);if(a.fc){var b=a.fc;a.fc=null;b.abort();b.dispose()}a.ee&&(a.ee=null)},p5=function(a,b){try{a.g.gv(a,b),a.g.ce(4)}catch(c){}},A5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;z5(a,b,function(e){e?c(!0):g.x.setTimeout(function(){A5(a,b,c,d,f)},f)})}},z5=function(a,b,c){var d=new window.Image;
d.onload=function(){try{B5(d),c(!0)}catch(e){}};
d.onerror=function(){try{B5(d),c(!1)}catch(e){}};
d.onabort=function(){try{B5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{B5(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},B5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},C5=function(a){this.g=a;
this.l=new g5},E5=function(a){var b=D5(a.g,a.Sh,"/mail/images/cleardot.gif");
m4(b);A5(b.toString(),5E3,(0,g.A)(a.az,a),3,2E3);a.ce(1)},G5=function(a){var b=a.g.I;
if(null!=b)n5(5),b?(n5(11),F5(a.g,a,!1)):(n5(12),F5(a.g,a,!0));else if(a.wd=new h5(a,void 0,void 0,void 0),a.wd.wg=a.Vm,b=a.g,b=D5(b,b.bj()?a.ni:null,a.Xm),n5(5),!g.vd||g.yc(10))n4(b,"TYPE","xmlhttp"),k5(a.wd,b,!1,a.ni,!1);else{n4(b,"TYPE","html");var c=a.wd;a=!!a.ni;c.nh=3;c.Hf=m4(b.clone());v5(c,a)}},H5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new g5;this.H=a||null;this.I=null!=b?b:null;this.C=c||!1},jja=function(a,b){this.g=a;
this.map=b;this.context=null},I5=function(a){g.Ne.call(this,"statevent",a)},J5=function(a,b){g.Ne.call(this,"timingevent",a);
this.size=b},K5=function(a){g.Ne.call(this,"serverreachability",a)},O5=function(a){L5(a);
if(3==a.g){var b=a.Qi++,c=a.ek.clone();g.$o(c,"SID",a.o);g.$o(c,"RID",b);g.$o(c,"TYPE","terminate");M5(a,c);b=new h5(a,a.o,b,void 0);b.nh=2;b.Hf=m4(c.clone());(new window.Image).src=b.Hf;b.Ch=(0,g.G)();l5(b)}N5(a)},Q5=function(a){a.kz(1,0);
a.ek=D5(a,null,a.Um);P5(a)},L5=function(a){a.Af&&(a.Af.abort(),a.Af=null);
a.Kb&&(a.Kb.cancel(),a.Kb=null);a.Ne&&(g.x.clearTimeout(a.Ne),a.Ne=null);R5(a);a.cd&&(a.cd.cancel(),a.cd=null);a.Cf&&(g.x.clearTimeout(a.Cf),a.Cf=null)},S5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new jja(a.HE++,b));2!=a.g&&3!=a.g||P5(a)},P5=function(a){a.cd||a.Cf||(a.Cf=x5((0,g.A)(a.lv,a),0),a.jh=0)},V5=function(a,b){if(1==a.g){if(!b){a.Qi=Math.floor(1E5*Math.random());
var c=a.Qi++,d=new h5(a,"",c,void 0);d.wg=null;var e=T5(a),f=a.ek.clone();g.$o(f,"RID",c);g.$o(f,"CVER","1");M5(a,f);j5(d,f,e);a.cd=d;a.g=2}}else 3==a.g&&(b?U5(a,b):0==a.l.length||a.cd||U5(a))},U5=function(a,b){if(b)if(6<a.ng){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Qi-1;var d=T5(a)}else c=b.F,d=b.Ng;else c=a.Qi++,d=T5(a);var e=a.ek.clone();g.$o(e,"SID",a.o);g.$o(e,"RID",c);g.$o(e,"AID",a.rh);M5(a,e);c=new h5(a,a.o,c,a.jh+1);c.wg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.cd=c;j5(c,e,d)},M5=function(a,b){if(a.Hc){var c=a.Hc.tr();
c&&g.Rb(c,function(a,c){g.$o(b,c,a)})}},T5=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.ng&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.ng?e:f-d;try{g.Rb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},W5=function(a){a.Kb||a.Ne||(a.F=1,a.Ne=x5((0,g.A)(a.kv,a),0),a.bh=0)},Y5=function(a){if(a.Kb||a.Ne||3<=a.bh)return!1;
a.F++;a.Ne=x5((0,g.A)(a.kv,a),X5(a,a.bh));a.bh++;return!0},F5=function(a,b,c){a.Ol=c;
a.pe=b.Te;a.C||Q5(a)},R5=function(a){null!=a.pg&&(g.x.clearTimeout(a.pg),a.pg=null)},X5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$5=function(a,b){if(2==b||9==b){var c=null;
a.Hc&&(c=null);var d=(0,g.A)(a.yJ,a);c||(c=new g.Qo("//www.google.com/images/cleardot.gif"),m4(c));z5(c.toString(),1E4,d)}else n5(2);Z5(a,b)},Z5=function(a,b){a.g=0;
a.Hc&&a.Hc.Cq(b);N5(a);L5(a)},N5=function(a){a.g=0;
a.pe=-1;if(a.Hc)if(0==a.A.length&&0==a.l.length)a.Hc.tm();else{g.Za(a.A);var b=g.Za(a.l);a.A.length=0;a.l.length=0;a.Hc.tm(b)}},D5=function(a,b,c){var d=g.ap(c);
if(""!=d.g)b&&g.So(d,b+"."+d.g),g.To(d,d.B);else{var e=window.location;d=Ria(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Zh&&g.Rb(a.Zh,function(a,b){g.$o(d,b,a)});
g.$o(d,"VER",a.ng);M5(a,d);return d},x5=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},n5=function(a){a6.dispatchEvent(new I5(a6,a))},b6=function(){},kja=function(a,b){this.action=a;
this.params=b||{}},c6=function(a,b){g.I.call(this);
this.g=new g.P(this.cI,0,this);g.J(this,this.g);this.zc=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},d6=function(a,b,c){this.L=a;
this.C=b;this.o=new g.Sq;this.l=new c6(this.XJ,this);this.g=null;this.K=!1;this.B=null;this.I="";this.H=this.A=0;this.F=[];this.O=c||!1},lja=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Ol,sessionId:a.g.o,arrayId:a.g.rh}},e6=function(a,b){a.H=b||0;
a.l.stop();a.g&&(3==a.g.g&&V5(a.g),O5(a.g));a.H=0},f6=function(a){return!!a.g&&3==a.g.g},mja=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},g6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Lg(a)||"";b&&(this.port=":"+b);this.domain=g.Kg(a)||"";a=g.Pb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Kb(a,"10.0")&&(this.l=!1))},h6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Ug(c+b,{})},i6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,fb:g.B(a.A,d,!0),onError:g.B(a.o,e),Xc:g.B(a.B,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.qs(b,a)},nja=function(){var a=j6;
k6();l6.push(a);m6(l6)},n6=function(a,b){k6();
var c=l6,d=oja(a,String(b));0==c.length?pja(d):(m6(c),(0,g.F)(c,function(a){a(d)}))},k6=function(){l6||(l6=g.z("yt.mdx.remote.debug.handlers_")||[],g.y("yt.mdx.remote.debug.handlers_",l6,void 0))},pja=function(a){var b=(o6+1)%50;
o6=b;p6[b]=a;q6||(q6=49==b)},m6=function(a){var b=p6;
if(b[0]){var c=o6,d=q6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.F)(a,function(a){a(e)})}while(d!=c);
p6=Array(50);o6=-1;q6=!1}},oja=function(a,b){var c=((0,g.G)()-qja)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},r6=function(a){g.R.call(this);
this.F=a;this.g=[]},s6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},rja=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Ld)(a.g,function(a){return!!L4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=s6(a,b[d])||c;return c},sja=function(a,b){var c=a.g.length;
a.g=(0,g.Ld)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},t6=function(a,b,c,d){g.R.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.za=window.NaN},v6=function(a){r6.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;u6(this);this.info("Initializing with "+J4(this.g))},w6=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=h6(a.o,"/pairing/get_lounge_token_batch");
i6(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.Kz,a),(0,g.A)(a.Jz,a))}},u6=function(a){var b=H4(T4());
b=(0,g.Ld)(b,function(a){return!a.uuid});
return rja(a,b)},x6=function(a,b){$ia((0,g.H)(a.g,G4));
b&&U4()},z6=function(a,b){g.R.call(this);
this.C=b;var c=g.Xu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Sa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;y6("Initialized with "+g.xg(this.g))},A6=function(a,b,c){var d=h6(a.B,"/pairing/get_screen_availability");
i6(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},B6=function(a,b){a:if(g.Wb(b)!=g.Wb(a.g))var c=!1;
else{c=g.Yb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(y6("Updated online screens: "+g.xg(a.g)),a.g=b,a.P("screenChange"));tja(a)},C6=function(a){(0,window.isNaN)(a.o)||g.bs(a.o);
a.o=g.$r((0,g.A)(a.ip,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},y6=function(a){n6("OnlineScreenService",a)},D6=function(a){var b={};
(0,g.F)(a.C(),function(a){a.token?b[a.token]=a.id:this.Cb("Requesting availability of screen w/o lounge token.")});
return b},tja=function(a){a=g.Yb(g.Sb(a.g,function(a){return a}));
g.gb(a);a.length?g.Wu("yt-remote-online-screen-ids",a.join(","),60):g.Yu("yt-remote-online-screen-ids")},E6=function(a){r6.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};uja(this)},G6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.rd();if(k=(c?M4(k,c):null)||M4(k,b)){k.uuid=b;var l=F6(a,k);A6(a.l,l,function(a){e(a?l:null)})}else c?vja(a,c,(0,g.A)(function(a){var f=F6(this,new E4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));A6(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},H6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},vja=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,fb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.qs(h6(a.C,"/pairing/get_lounge_token_batch"),e)},I6=function(a){a.g=a.o.rd();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+J4(a.g))},uja=function(a){J6(a);
a.o=new v6(a.C);a.o.subscribe("screenChange",(0,g.A)(a.Xz,a));I6(a);a.A=H4(g.Xu("yt-remote-automatic-screen-cache")||[]);J6(a);a.info("Initializing automatic screens: "+J4(a.A));a.l=new z6(a.C,(0,g.A)(a.rd,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.P("onlineScreenChange")},a))},F6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=M4(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Wu("yt-remote-automatic-screen-cache",(0,g.H)(a.A,G4)));J6(a);a.B[b.uuid]=b.id;g.Wu("yt-remote-device-id-map",a.B,31536E3);return b},J6=function(a){a.B=g.Xu("yt-remote-device-id-map")||{}},K6=function(a,b,c){g.R.call(this);
this.O=c;this.I=a;this.l=b;this.o=null},L6=function(a,b){n6(a.O,b)},N6=function(a,b){K6.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.dK,this);this.B=(0,g.A)(this.EI,this);this.A=g.$r((0,g.A)(function(){M6(this,null)},this),12E4)},wja=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.xg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.wa,(0,g.A)(function(){L6(this,"Failed to send message: getMdxSessionStatus.")},a)):L6(a,"Sending yt message without session: "+g.xg(b))},M6=function(a,b){g.bs(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.fl,a),d=(0,g.A)(a.td,a);a.Cr(b,c,d,5)}}else a.td(Error("Waiting for session status timed out."))},O6=function(a,b,c){K6.call(this,a,b,"DialSession");
this.A=this.H=null;this.K="";this.U=c;this.B=null;this.F=g.wa;this.C=window.NaN;this.L=(0,g.A)(this.gK,this);this.g=g.wa},P6=function(a){a.g=a.I.xx(a.K,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.wa;
this.fl(a)},a),(0,g.A)(function(a){this.g=g.wa;
this.td(a)},a))},Q6=function(a){var b={};
b.pairingCode=a.K;b.theme=a.U;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}X4()&&(b.env_useStageMdx=1);return g.Sg(b)},R6=function(a,b){K6.call(this,a,b,"ManualSession");
this.g=g.$r((0,g.A)(this.th,this,null),150)},S6=function(a,b,c,d){g.R.call(this);
this.l=a;this.F=b||"233637DE";this.C=c||"cl";this.H=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.tH,this)},T6=function(a,b){return b?g.Na(a.o,function(a){return F4(b,a.label)},a):null},U6=function(a){n6("Controller",a)},j6=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},V6=function(a){return a.B||!!a.o.length||!!a.g},W6=function(a,b,c){b!=a.g&&(g.Le(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.jv,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.th(null)):a.P("yt-remote-cast2-session-change",null))},X6=function(a){var b=a.l.wx(),c=a.g&&a.g.l;
a=(0,g.H)(b,function(a){c&&F4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=T6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Aja=function(a,b,c,d,e,f,k){xja()?yja(b,e,f,k)&&(Z6(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?$6(a,c):(window.__onGCastApiAvailable=function(b,d){b?$6(a,c):(a7("Failed to load cast API: "+d),b7(!1),Z6(!1),g.Yu("yt-remote-cast-available"),g.Yu("yt-remote-cast-receiver"),c7(),c(!1))},
d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):dja():d5("CriOS")?gja():d5("Android")&&d5("Chrome/")&&window.navigator.presentation?hja():window.chrome&&window.navigator.presentation&&!d5("Edge")?(e5(),a5(zja.map(eja))):b5())):Y6("Cannot initialize because not running Chrome")},c7=function(){Y6("dispose");
var a=d7();a&&a.dispose();g.y("yt.mdx.remote.cloudview.instance_",null,void 0);e7(!1);g.iu(f7);f7.length=0},g7=function(){return!!g.Xu("yt-remote-cast-installed")},h7=function(){var a=g.Xu("yt-remote-cast-receiver");
return a?a.friendlyName:null},i7=function(){Y6("clearCurrentReceiver");
g.Yu("yt-remote-cast-receiver")},j7=function(){return g7()?d7()?d7().getCastSession():(a7("getCastSelector: Cast is not initialized."),null):(a7("getCastSelector: Cast API is not installed!"),null)},l7=function(){g7()?d7()?k7()?(Y6("Requesting cast selector."),d7().requestSession()):(Y6("Wait for cast API to be ready to request the session."),f7.push(g.hu("yt-remote-cast2-api-ready",l7))):a7("requestCastSelector: Cast is not initialized."):a7("requestCastSelector: Cast API is not installed!")},m7=
function(a,b){k7()?d7().setConnectedScreenStatus(a,b):a7("setConnectedScreenStatus called before ready.")},xja=function(){var a=0<=g.Pb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Ky||a},Bja=function(a,b){d7().init(a,b)},yja=function(a,b,c,d){var e=!1;
d7()||(a=new S6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Wu("yt-remote-cast-available",a);g.lu("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){Y6("onReceiverSelected: "+a.friendlyName);
g.Wu("yt-remote-cast-receiver",a);g.lu("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){Y6("onReceiverResumed: "+a.friendlyName);
g.Wu("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){Y6("onSessionChange: "+I4(a));
a||g.Yu("yt-remote-cast-receiver");g.lu("yt-remote-cast2-session-change",a)}),g.y("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
Y6("cloudview.createSingleton_: "+e);return e},d7=function(){return g.z("yt.mdx.remote.cloudview.instance_")},$6=function(a,b){b7(!0);
Z6(!1);Bja(a,function(a){a?(e7(!0),g.ku("yt-remote-cast2-api-ready")):(a7("Failed to initialize cast API."),b7(!1),g.Yu("yt-remote-cast-available"),g.Yu("yt-remote-cast-receiver"),c7());b(a)})},Y6=function(a){n6("cloudview",a)},a7=function(a){n6("cloudview",a)},b7=function(a){Y6("setCastInstalled_ "+a);
g.Wu("yt-remote-cast-installed",a)},k7=function(){return!!g.z("yt.mdx.remote.cloudview.apiReady_")},e7=function(a){Y6("setApiReady_ "+a);
g.y("yt.mdx.remote.cloudview.apiReady_",a,void 0)},Z6=function(a){g.y("yt.mdx.remote.cloudview.initializing_",a,void 0)},n7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.H=0;this.l=null;this.hasNext=this.qe=!1;this.K=this.I=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},o7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.qe=!1;a.hasNext=!1;a.H=0;a.F=(0,g.G)();a.B=0;a.o=0;a.I=0;a.K=0;a.A=window.NaN;a.C=!1},p7=function(a){return 1==a.g?((0,g.G)()-a.F)/1E3:0},q7=function(a,b){a.H=b;
a.F=(0,g.G)()},r7=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.F)/1E3+a.H;
case -1E3:return 0}return a.H},s7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&o7(a)},t7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ic(a.l);b.hasPrevious=a.qe;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.I;b.loadedTime=a.K;b.liveIngestionTime=a.A;return b},w7=function(a,b){g.R.call(this);
this.g=0;this.A=a;this.C=[];this.B=new B4;this.o=this.l=null;this.I=(0,g.A)(this.nF,this);this.F=(0,g.A)(this.Ti,this);this.H=(0,g.A)(this.mF,this);this.K=(0,g.A)(this.AF,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Op,this),u7(this))):c=3;0!=c&&(b?this.Op(c):g.$r((0,g.A)(function(){this.Op(c)},this),0));
var d=j7();d&&v7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},x7=function(a){return new n7(a.A.getPlayerContextData())},u7=function(a){(0,g.F)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.B(this.qH,a),this))},a)},y7=function(a){(0,g.F)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},z7=function(a,b){var c=a.B;
50>c.g.length+c.l.length&&a.B.l.push(b)},B7=function(a,b,c){var d=x7(a);
q7(d,c);-1E3!=d.g&&(d.g=b);A7(a,d)},C7=function(a,b,c){a.A.sendMessage(b,c)},A7=function(a,b){y7(a);
a.A.setPlayerContextData(t7(b));u7(a)},v7=function(a,b){a.o&&(a.o.removeUpdateListener(a.I),a.o.removeMediaListener(a.F),a.Ti(null));
a.o=b;a.o&&(n6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.I),a.o.addMediaListener(a.F),a.o.media.length&&a.Ti(a.o.media[0]))},D7=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=x7(a);b.contentId!=d.videoId&&n6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;q7(d,a.l.getEstimatedTime());A7(a,d)}else n6("CP","No cast media video. Ignoring state update.")},E7=function(a,b,c){return(0,g.A)(function(a){this.Cb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Cb("Retrying "+b+" using MDx browser channel."),C7(this,b,c))},a)},F7=function(a,b,c){g.R.call(this);
this.B=window.NaN;this.U=!1;this.K=this.I=this.L=this.O=window.NaN;this.T=[];this.A=this.F=this.o=this.Ka=this.g=null;this.ua=a;this.T.push(g.Ft(window,"beforeunload",(0,g.A)(this.Dz,this)));this.l=[];this.Ka=new n7;this.ba=b.id;this.g=Cja(this,c);this.g.subscribe("handlerOpened",this.rF,this);this.g.subscribe("handlerClosed",this.oF,this);this.g.subscribe("handlerError",this.pF,this);this.g.subscribe("handlerMessage",this.qF,this);mja(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Ka.videoId;g.bv()&&g.Wu("yt-remote-session-video-id",a)},this)},G7=function(a){n6("conn",a)},Cja=function(a,b){return new d6(h6(a.ua,"/bc"),b)},H7=function(a,b){a.P("proxyStateChange",b)},Dja=function(a){a.B=g.$r((0,g.A)(function(){G7("Connecting timeout");
this.C(1)},a),2E4)},I7=function(a){g.bs(a.B);
a.B=window.NaN},J7=function(a){g.bs(a.O);
a.O=window.NaN},Eja=function(a){K7(a);
a.L=g.$r((0,g.A)(function(){L7(this,"getNowPlaying")},a),2E4)},K7=function(a){g.bs(a.L);
a.L=window.NaN},N7=function(a,b){b&&(I7(a),J7(a));
b==(f6(a.g)&&(0,window.isNaN)(a.B))?b&&(H7(a,1),L7(a,"getSubtitlesTrack")):b?(a.V()&&a.Ka.reset(),H7(a,1),L7(a,"getNowPlaying"),M7(a)):a.C(1)},Fja=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ka.videoId&&(g.dc(b.params)?a.Ka.l=null:a.Ka.l=b.params,a.P("remotePlayerChange"))},O7=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Ka.listId=b.params.listId||a.Ka.listId;s7(a.Ka,c,d);a.P("remoteQueueChange")},Gja=function(a,b){b.params=b.params||{};
O7(a,b);P7(a,b);a.P("autoplayDismissed")},P7=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
q7(a.Ka,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Ka.g&&(c=-1E3);a.Ka.g=c;c=Number(b.params.loadedTime);a.Ka.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Ka.I=(0,window.isNaN)(c)?0:c;c=a.Ka;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Ka;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Ka.g?Eja(a):K7(a);
a.P("remotePlayerChange")},Hja=function(a,b){if(-1E3!=a.Ka.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ka.g=c;c=(0,window.parseInt)(b.params.currentTime,10);q7(a.Ka,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},Ija=function(a,b){var c="true"==b.params.muted;
a.Ka.volume=(0,window.parseInt)(b.params.volume,10);a.Ka.muted=c;a.P("remotePlayerChange")},Jja=function(a,b){a.F=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},Kja=function(a,b){var c="true"==b.params.hasNext;
a.Ka.qe="true"==b.params.hasPrevious;a.Ka.hasNext=c;a.P("previousNextChange")},M7=function(a){g.bs(a.K);
a.K=g.$r((0,g.A)(a.C,a,1),864E5)},L7=function(a,b,c){c?G7("Sending: action="+b+", params="+g.xg(c)):G7("Sending: action="+b);
a.g.sendMessage(b,c)},Q7=function(a){r6.call(this,"ScreenServiceProxy");
this.yc=a;this.l=[];this.l.push(this.yc.$_s("screenChange",(0,g.A)(this.bK,this)));this.l.push(this.yc.$_s("onlineScreenChange",(0,g.A)(this.XG,this)))},Pja=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Tr("MDX_CONFIG")||b;Tia();R4();R7||(R7=new g6(b?b.loungeApiHost:void 0),X4()&&(R7.g="/api/loungedev"));S7||(S7=g.z("yt.mdx.remote.deferredProxies_")||[],g.y("yt.mdx.remote.deferredProxies_",S7,void 0));Lja();var c=T7();if(!c){var d=new E6(R7);g.y("yt.mdx.remote.screenService_",d,void 0);c=T7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Aja(a,d,function(a){a?U7()&&m7(U7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.lu("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.z("yt.mdx.remote.initialized_")&&(g.y("yt.mdx.remote.initialized_",!0,void 0),V7("Initializing: "+g.xg(b)),W7.push(g.hu("yt-remote-cast2-availability-change",function(){g.lu("yt-remote-receiver-availability-change")})),W7.push(g.hu("yt-remote-cast2-receiver-selected",function(){X7(null);
g.lu("yt-remote-auto-connect","cast-selector-receiver")})),W7.push(g.hu("yt-remote-cast2-receiver-resumed",function(){g.lu("yt-remote-receiver-resumed","cast-selector-receiver")})),W7.push(g.hu("yt-remote-cast2-session-change",Mja)),W7.push(g.hu("yt-remote-connection-change",function(a){a?m7(U7(),"YouTube TV"):Y7()||(m7(null,null),i7())})),a=Z7(),b.isAuto&&(a.id+="#dial"),g.Rs("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),V7(" -- with channel params: "+
g.xg(a)),Nja(a),c.start(),U7()||Oja())},Qja=function(){var a=$7();
g7()&&g.Xu("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},$7=function(){var a=T7().yc.$_gos();
var b=a8();b&&b8()&&(L4(a,b)||a.push(b));return Yia(a)},c8=function(){var a=Rja();
!a&&g7()&&h7()&&(a={key:"cast-selector-receiver",name:h7()});return a},Rja=function(){var a=$7(),b=a8();
b||(b=Y7());return g.Na(a,function(a){return b&&F4(b,a.key)?!0:!1})},a8=function(){var a=U7();
if(!a)return null;var b=T7().rd();return M4(b,a)},Mja=function(a){V7("remote.onCastSessionChange_: "+I4(a));
if(a){var b=a8();b&&b.id==a.id?m7(b.id,"YouTube TV"):(b&&d8(),e8(a,1))}else b8()&&d8()},d8=function(){k7()?d7().stopSession():a7("stopSession called before API ready.");
var a=b8();a&&(a.disconnect(1),f8(null))},g8=function(){var a=b8();
return!!a&&3!=a.getProxyState()},V7=function(a){n6("remote",a)},T7=function(){if(!h8){var a=g.z("yt.mdx.remote.screenService_");
h8=a?new Q7(a):null}return h8},U7=function(){return g.z("yt.mdx.remote.currentScreenId_")},i8=function(a){g.y("yt.mdx.remote.currentScreenId_",a,void 0)},j8=function(){return g.z("yt.mdx.remote.connectData_")},X7=function(a){g.y("yt.mdx.remote.connectData_",a,void 0)},b8=function(){return g.z("yt.mdx.remote.connection_")},f8=function(a){var b=b8();
X7(null);a||i8("");g.y("yt.mdx.remote.connection_",a,void 0);S7&&((0,g.F)(S7,function(b){b(a)}),S7.length=0);
b&&!a?g.lu("yt-remote-connection-change",!1):!b&&a&&g.lu("yt-remote-connection-change",!0)},Y7=function(){var a=g.bv();
if(!a)return null;var b=T7().rd();return M4(b,a)},e8=function(a,b){a8()&&a8();
i8(a.id);var c=new F7(R7,a,Z7());c.connect(b,j8());c.subscribe("beforeDisconnect",function(a){g.lu("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){b8()&&f8(null)});
f8(c)},Oja=function(){var a=Y7();
a?(V7("Resume connection to: "+I4(a)),e8(a,0)):(V4(),i7(),V7("Skipping connecting because no session screen found."))},Lja=function(){var a=Z7();
if(g.dc(a)){a=Q4();var b=g.Xu("yt-remote-session-name")||"",c=g.Xu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.y("yt.mdx.remote.channelParams_",a,void 0)}},Z7=function(){return g.z("yt.mdx.remote.channelParams_")||{}},Nja=function(a){a?(g.Wu("yt-remote-session-app",a.app),g.Wu("yt-remote-session-name",a.name)):(g.Yu("yt-remote-session-app"),g.Yu("yt-remote-session-name"));
g.y("yt.mdx.remote.channelParams_",a,void 0)},k8=function(a,b,c){g.I.call(this);
this.H=a;this.l=b;this.o=new g.Rt(this);g.J(this,this.o);this.o.M(b,"onCaptionsTrackListChanged",this.qG);this.o.M(b,"captionschanged",this.lF);this.o.M(b,"captionssettingschanged",this.Bw);this.o.M(b,"videoplayerreset",this.il);this.o.M(b,"mdxautoplaycancel",this.Yy);this.T=this.o.M(b,"onVolumeChange",this.Wu);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.fv,this);c.subscribe("remotePlayerChange",this.Ui,this);c.subscribe("remoteQueueChange",this.il,this);c.subscribe("autoplayUpNext",this.Gu,
this);c.subscribe("previousNextChange",this.cv,this);c.subscribe("nowAutoplaying",this.Yu,this);c.subscribe("autoplayDismissed",this.Fu,this);this.suggestion=null;this.I=new g.mE(64);this.A=new g.P(this.xw,500,this);g.J(this,this.A);this.B=new g.P(this.yw,1E3,this);g.J(this,this.B);this.L=new f5(this.IJ,0,this);g.J(this,this.L);this.C={};this.O=new g.P(this.gx,1E3,this);g.J(this,this.O);this.K=new g.fm(this.kD,1E3,this);g.J(this,this.K);this.U=g.wa;this.Bw();this.il();this.Ui()},l8=function(a,b){var c=
a.H,d=a.l.Y().lengthSeconds;
c.F=b||0;c.g.P("progresssync",b,d)},n8=function(a){l8(a,0);
a.A.stop();m8(a,new g.mE(64))},p8=function(a,b){if(o8(a)&&!a.F){var c=null;
b&&(c={style:a.l.Kg()},g.kc(c,b));a.g.ow(a.l.Y(1).videoId,c);a.C=x7(a.g).l}},q8=function(a,b){var c=a.l.Be();
if(c){var d=c.Pa;var e=c.listId.toString()}var f=a.l.Y(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.ph;var m=x7(c),n=e||m.listId;l=l||0;var p={videoId:k,currentIndex:l};s7(m,k,l);g.t(b)&&(q7(m,b),p.currentTime=b);g.t(n)&&(p.listId=n);null!=d&&(p.playerParams=d);null!=f&&(p.clickTrackingParams=f);C7(c,"setPlaylist",p);e||A7(c,m);m8(a,new g.mE(1))},r8=function(a,b){if(b){var c=a.l.Ob("captions","tracklist",{hs:1});
c&&c.length?(a.l.Wc("captions","track",b),a.F=!1):(a.l.Fi("captions"),a.F=!0)}else a.l.Wc("captions","track",{})},o8=function(a){return x7(a.g).videoId==a.l.Y(1).videoId},m8=function(a,b){a.B.stop();
var c=a.I;if(!g.uE(c,b)){var d=g.V(b,2);d!=g.V(a.I,2)&&g.BK(a.l,d);a.I=b;s8(a.H,c,b)}},u8=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",G:[{D:"div",J:"ytp-remote-display-status",G:[{D:"div",J:"ytp-remote-display-status-icon",G:[g.oO()]},{D:"div",J:"ytp-remote-display-status-text",G:["{{statustext}}"]}]}]});this.g=new g.iP(this,250);g.J(this,this.g);this.l=a;this.M(a,"presentingplayerstatechange",this.o);t8(this,g.yK(a))},t8=function(a,b){if(3==a.l.Ga()){var c={RECEIVER_NAME:a.l.Ob("remote","currentReceiver").name};
c=g.V(b,128)?g.S("YTP_MDX_STATUS_ERROR_2",c):g.vE(b)||g.V(b,4)?g.S("YTP_MDX_STATUS_PLAYING_2",c):g.S("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.g.show()}else a.g.hide()},v8=function(a,b){g.oT.call(this,g.S("YTP_MDX_TITLE"),0,a,b);
this.g=a;this.F={};this.M(a,"onMdxReceiversChange",this.I);this.M(a,"presentingplayerstatechange",this.I);this.I()},w8=function(a){g.dL.call(this,a);
g.dv({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:K4(),name:g.S("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.K=this.l=null;this.I=[this.o];this.A=this.o;this.H=new g.mE(64);this.F=0;if(!g.VB(g.W(this.g))){a=
this.g;var b=g.Kw(a);b&&(b=b.Kk())&&(b=new v8(a,b),g.J(this,b));b=new u8(a);g.J(this,b);g.TK(a,b.element,4)}},s8=function(a,b,c){a.H=c;
a.g.P("presentingplayerstatechange",new g.BE(c,b))},x8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)d8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.Y(1),e=d.videoId;if(c||e){var f=a.g.Be();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Eb(l).videoId}else k=[e];f=a.g.xa(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.ph,index:Math.max(a.g.it(),0),currentTime:0==f?void 0:f}}else c=null;V7("Connecting to: "+g.xg(b));"cast-selector-receiver"==b.key?(X7(c||null),k7()?d7().setLaunchParams(c||null):a7("setLaunchParams called before ready.")):!c&&g8()&&U7()==
b.key?g.lu("yt-remote-connection-change",!0):(d8(),X7(c||null),c=T7().rd(),(c=M4(c,b.key))&&e8(c,1))}},Oia=/^https?$/i,Sja=["POST",
"PUT"];g.E(z4,g.rf);g.h=z4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.I+"; newUri="+a);b=b?b.toUpperCase():"GET";this.I=a;this.B="";this.A=0;this.X=b;this.T=!1;this.l=!0;this.g=this.U?r4(this.U):r4(g.XW);this.O=this.U?q4(this.U):q4(g.XW);this.g.onreadystatechange=(0,g.A)(this.Mr,this);try{o4(s4(this,"Opening Xhr")),this.ba=!0,this.g.open(b,String(a),!0),this.ba=!1}catch(f){o4(s4(this,"Error opening Xhr: "+f.message));w4(this,f);return}a=c||"";var e=this.headers.clone();
d&&Lia(d,function(a,b){e.set(b,a)});
d=g.Na(e.pd(),Mia);c=g.x.FormData&&a instanceof g.x.FormData;!g.Sa(Sja,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.aa&&(this.g.responseType=this.aa);"withCredentials"in this.g&&this.g.withCredentials!==this.V&&(this.g.withCredentials=this.V);try{t4(this),0<this.C&&(this.L=Nia(this.g),o4(s4(this,"Will abort after "+this.C+"ms if incomplete, xhr2 "+this.L)),this.L?(this.g.timeout=this.C,this.g.ontimeout=(0,g.A)(this.Nr,this)):this.F=g.ng(this.Nr,this.C,this)),o4(s4(this,"Sending request")),this.H=!0,this.g.send(a),this.H=!1}catch(f){o4(s4(this,"Send error: "+f.message)),w4(this,f)}};
g.h.Nr=function(){"undefined"!=typeof g.yW&&this.g&&(this.B="Timed out after "+this.C+"ms, aborting",this.A=8,s4(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(s4(this,"Aborting"),this.l=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),v4(this))};
g.h.R=function(){this.g&&(this.l&&(this.l=!1,this.o=!0,this.g.abort(),this.o=!1),v4(this,!0));z4.wa.R.call(this)};
g.h.Mr=function(){this.ga()||(this.ba||this.H||this.o?y4(this):this.sH())};
g.h.sH=function(){y4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<x4(this)?this.g.status:-1}catch(a){return-1}};
var u5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},t5={"'":"\\'"},Tja={};g.h=B4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.l.length};
g.h.clear=function(){this.g=[];this.l=[]};
g.h.contains=function(a){return g.Sa(this.g,a)||g.Sa(this.l,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Mea)(b,a);0<=c?(g.Va(b,c),b=!0):b=!1;return b||g.Wa(this.l,a)};
g.h.hc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};
var Wia={pK:"atp",FM:"ska",rM:"que",OL:"mus",EM:"sus"};D4.prototype.Pj=function(){var a=new D4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var W4,P4="",c5=Y4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",fja=Y4("loadCastFramework")||Y4("loadCastApplicationFramework"),zja=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.E(f5,g.I);g.h=f5.prototype;g.h.Az=function(a){this.A=arguments;this.g=!1;this.za?this.o=(0,g.G)()+this.zc:this.za=g.ng(this.B,this.zc)};
g.h.stop=function(){this.za&&(g.x.clearTimeout(this.za),this.za=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.R=function(){this.stop();f5.wa.R.call(this)};
g.h.Bz=function(){this.o?(this.za=g.ng(this.B,this.o-(0,g.G)()),this.o=null):(this.za=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};g5.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
g5.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=h5.prototype;g.h.wg=null;g.h.de=!1;g.h.Ph=null;g.h.Mp=null;g.h.Ch=null;g.h.nh=null;g.h.Hf=null;g.h.ag=null;g.h.Ng=null;g.h.fc=null;g.h.ij=0;g.h.ee=null;g.h.Pl=null;g.h.If=null;g.h.oi=-1;g.h.aw=!0;g.h.mg=!1;g.h.Ym=0;g.h.sl=null;var o5={},m5={};g.h=h5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.SI=function(a){a=a.target;var b=this.sl;b&&3==x4(a)?b.lh():this.nx(a)};
g.h.nx=function(a){try{if(a==this.fc)a:{var b=x4(this.fc),c=this.fc.A,d=this.fc.getStatus();if(g.vd&&!g.yc(10)||g.xd&&!g.wc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.zh&&!A4(this.fc))break a;this.mg||4!=b||7==c||(8==c||0>=d?this.g.ce(3):this.g.ce(2));y5(this);var e=this.fc.getStatus();this.oi=e;var f=A4(this.fc);(this.de=200==e)?(4==b&&q5(this),this.B?(s5(this,b,f),g.zh&&this.de&&3==b&&(this.ea.fa(this.l,"tick",this.KI),this.l.start())):p5(this,f),this.de&&!this.mg&&(4==b?this.g.dl(this):(this.de=
!1,l5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.If=3,n5(13)):(this.If=0,n5(14)),q5(this),r5(this))}}catch(k){this.fc&&A4(this.fc)}finally{}};
g.h.KI=function(){var a=x4(this.fc),b=A4(this.fc);this.ij<b.length&&(y5(this),s5(this,a,b),this.de&&4!=a&&l5(this))};
g.h.jI=function(a){x5((0,g.A)(this.iI,this,a),0)};
g.h.iI=function(a){this.mg||(y5(this),p5(this,a),l5(this))};
g.h.qv=function(a){x5((0,g.A)(this.hI,this,a),0)};
g.h.hI=function(a){this.mg||(q5(this),this.de=a,this.g.dl(this),this.g.ce(4))};
g.h.cancel=function(){this.mg=!0;q5(this)};
g.h.uI=function(){this.Ph=null;var a=(0,g.G)();0<=a-this.Mp?(2!=this.nh&&this.g.ce(3),q5(this),this.If=2,n5(18),r5(this)):w5(this,this.Mp-a)};g.h=C5.prototype;g.h.Vm=null;g.h.wd=null;g.h.tl=!1;g.h.Lr=null;g.h.bk=null;g.h.Wm=null;g.h.Xm=null;g.h.Fd=null;g.h.Te=-1;g.h.ni=null;g.h.Sh=null;g.h.connect=function(a){this.Xm=a;a=D5(this.g,null,this.Xm);n5(3);this.Lr=(0,g.G)();var b=this.g.H;null!=b?(this.ni=b[0],(this.Sh=b[1])?(this.Fd=1,E5(this)):(this.Fd=2,G5(this))):(n4(a,"MODE","init"),this.wd=new h5(this,void 0,void 0,void 0),this.wd.wg=this.Vm,k5(this.wd,a,!1,null,!0),this.Fd=0)};
g.h.az=function(a){if(a)this.Fd=2,G5(this);else{n5(4);var b=this.g;b.pe=b.Af.Te;$5(b,9)}a&&this.ce(2)};
g.h.Cm=function(a){return this.g.Cm(a)};
g.h.abort=function(){this.wd&&(this.wd.cancel(),this.wd=null);this.Te=-1};
g.h.Kr=function(){return!1};
g.h.gv=function(a,b){this.Te=a.oi;if(0==this.Fd)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.pe=this.Te;$5(c,2);return}this.ni=c[0];this.Sh=c[1]}else c=this.g,c.pe=this.Te,$5(c,2);else if(2==this.Fd)if(this.tl)n5(7),this.Wm=(0,g.G)();else if("11111"==b){if(n5(6),this.tl=!0,this.bk=(0,g.G)(),c=this.bk-this.Lr,!g.vd||g.yc(10)||500>c)this.Te=200,this.wd.cancel(),n5(12),F5(this.g,this,!0)}else n5(8),this.bk=this.Wm=(0,g.G)(),this.tl=!1};
g.h.dl=function(){this.Te=this.wd.oi;if(this.wd.de)0==this.Fd?this.Sh?(this.Fd=1,E5(this)):(this.Fd=2,G5(this)):2==this.Fd&&((!g.vd||g.yc(10)?!this.tl:200>this.Wm-this.bk)?(n5(11),F5(this.g,this,!1)):(n5(12),F5(this.g,this,!0)));else{0==this.Fd?n5(9):2==this.Fd&&n5(10);var a=this.g;a.pe=this.Te;$5(a,2)}};
g.h.bj=function(){return this.g.bj()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ce=function(a){this.g.ce(a)};g.h=H5.prototype;g.h.Zh=null;g.h.cd=null;g.h.Kb=null;g.h.Um=null;g.h.ek=null;g.h.uq=null;g.h.qk=null;g.h.Qi=0;g.h.HE=0;g.h.Hc=null;g.h.Cf=null;g.h.Ne=null;g.h.pg=null;g.h.Af=null;g.h.Ol=null;g.h.rh=-1;g.h.As=-1;g.h.pe=-1;g.h.jh=0;g.h.bh=0;g.h.ng=8;var a6=new g.rf;g.E(I5,g.Ne);g.E(J5,g.Ne);g.E(K5,g.Ne);g.h=H5.prototype;g.h.connect=function(a,b,c,d,e){n5(0);this.Um=b;this.Zh=c||{};d&&g.t(e)&&(this.Zh.OSID=d,this.Zh.OAID=e);this.C?(x5((0,g.A)(this.Rq,this,a),100),Q5(this)):this.Rq(a)};
g.h.Rq=function(a){this.Af=new C5(this);this.Af.Vm=null;this.Af.l=this.B;this.Af.connect(a)};
g.h.Kr=function(){return 0==this.g};
g.h.lv=function(a){this.Cf=null;V5(this,a)};
g.h.kv=function(){this.Ne=null;this.Kb=new h5(this,this.o,"rpc",this.F);this.Kb.wg=null;this.Kb.Ym=0;var a=this.uq.clone();g.$o(a,"RID","rpc");g.$o(a,"SID",this.o);g.$o(a,"CI",this.Ol?"0":"1");g.$o(a,"AID",this.rh);M5(this,a);if(!g.vd||g.yc(10))g.$o(a,"TYPE","xmlhttp"),k5(this.Kb,a,!0,this.qk,!1);else{g.$o(a,"TYPE","html");var b=this.Kb,c=!!this.qk;b.nh=3;b.Hf=m4(a.clone());v5(b,c)}};
g.h.gv=function(a,b){if(0!=this.g&&(this.Kb==a||this.cd==a))if(this.pe=a.oi,this.cd==a&&3==this.g)if(7<this.ng){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.Ne){if(this.Kb)if(this.Kb.Ch+3E3<this.cd.Ch)R5(this),this.Kb.cancel(),this.Kb=null;else break a;Y5(this);n5(19)}}else this.As=c[1],0<this.As-this.rh&&37500>c[2]&&this.Ol&&0==this.bh&&!this.pg&&(this.pg=x5((0,g.A)(this.hF,this),6E3));else $5(this,11)}else b!=Tja.QK.g&&$5(this,11);else if(this.Kb==a&&
R5(this),!g.qb(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.rh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.qk=e[2],e=e[3],null!=e?this.ng=e:this.ng=6,this.g=3,this.Hc&&this.Hc.Eq(),this.uq=D5(this,this.bj()?this.qk:null,this.Um),W5(this)):"stop"==e[0]&&$5(this,7):3==this.g&&("stop"==e[0]?$5(this,7):"noop"!=e[0]&&this.Hc&&this.Hc.Dq(e),this.bh=0)}}};
g.h.hF=function(){null!=this.pg&&(this.pg=null,this.Kb.cancel(),this.Kb=null,Y5(this),n5(20))};
g.h.dl=function(a){if(this.Kb==a){R5(this);this.Kb=null;var b=2}else if(this.cd==a)this.cd=null,b=1;else return;this.pe=a.oi;if(0!=this.g)if(a.de)1==b?(b=(0,g.G)()-a.Ch,a6.dispatchEvent(new J5(a6,a.Ng?a.Ng.length:0,b,this.jh)),P5(this),this.A.length=0):W5(this);else{var c=a.If,d;if(!(d=3==c||7==c||0==c&&0<this.pe)){if(d=1==b)this.cd||this.Cf||1==this.g||2<=this.jh?d=!1:(this.Cf=x5((0,g.A)(this.lv,this,a),X5(this,this.jh)),this.jh++,d=!0);d=!(d||2==b&&Y5(this))}if(d)switch(c){case 1:$5(this,5);break;
case 4:$5(this,10);break;case 3:$5(this,6);break;case 7:$5(this,12);break;default:$5(this,2)}}};
g.h.kz=function(a){if(!g.Sa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.yJ=function(a){a?n5(2):(n5(1),Z5(this,8))};
g.h.Cm=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new z4;a.V=!1;return a};
g.h.isActive=function(){return!!this.Hc&&this.Hc.isActive(this)};
g.h.ce=function(a){a6.dispatchEvent(new K5(a6,a))};
g.h.bj=function(){return!(!g.vd||g.yc(10))};
g.h=b6.prototype;g.h.Eq=function(){};
g.h.Dq=function(){};
g.h.Cq=function(){};
g.h.tm=function(){};
g.h.tr=function(){return{}};
g.h.isActive=function(){return!0};g.E(c6,g.I);g.h=c6.prototype;g.h.cI=function(){this.zc=Math.min(3E5,2*this.zc);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.zc+15E3*Math.random();g.zq(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.zc=5E3};g.E(d6,b6);g.h=d6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Dc=function(a){return this.o.Dc(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.Le(this.o),e6(this),g.Le(this.l),this.l=null)};
g.h.ga=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.I="";this.l.stop();this.B=a||null;this.A=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new H5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.O),e=this.g;e&&(e.Hc=null);d.Hc=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.rh):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.kc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):f6(this)&&S5(this.g,c)};
g.h.Eq=function(){this.l.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)S5(this.g,a[b])}this.P("handlerOpened")};
g.h.Cq=function(a){var b=2==a&&401==this.g.pe;4==a||b||this.l.start();this.P("handlerError",a)};
g.h.tm=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.tr=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.A&&(a.ui=""+this.A);0!=this.H&&(a.ui=""+this.H);this.B&&g.kc(a,this.B);return a};
g.h.Dq=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),O5(this.g)):this.P("handlerMessage",new kja(a[0],a[1]))};
g.h.XJ=function(){this.l.isActive();var a=this.g,b=0;a.Kb&&b++;a.cd&&b++;0!=b||this.connect(this.B,this.A)};g6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
g6.prototype.B=function(a){a(Error("request timed out"))};var qja=(0,g.G)(),l6=null,p6=Array(50),o6=-1,q6=!1;g.E(r6,g.R);r6.prototype.rd=function(){return this.g};
r6.prototype.contains=function(a){return!!L4(this.g,a)};
r6.prototype.get=function(a){return a?M4(this.g,a):null};
r6.prototype.info=function(a){n6(this.F,a)};g.E(t6,g.R);var y8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=t6.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.za)&&this.vx()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.za)||(g.bs(this.za),this.za=window.NaN)};
g.h.R=function(){this.stop();t6.wa.R.call(this)};
g.h.vx=function(){this.za=window.NaN;this.g=g.qs(h6(this.C,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.B},timeout:5E3,fb:(0,g.A)(this.ZJ,this),onError:(0,g.A)(this.YJ,this),Xc:(0,g.A)(this.aK,this)})};
g.h.ZJ=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new E4(c))};
g.h.YJ=function(a){this.g=null;a.status&&404==a.status?this.l>=y8.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=y8[this.l],this.za=g.$r((0,g.A)(this.vx,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.aK=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.E(v6,r6);g.h=v6.prototype;g.h.start=function(){u6(this)&&this.P("screenChange");!g.Xu("yt-remote-lounge-token-expiration")&&w6(this);g.bs(this.l);this.l=g.$r((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){u6(this);s6(this,a);x6(this,!1);this.P("screenChange");b(a);a.token||w6(this)};
g.h.remove=function(a,b){var c=u6(this);sja(this,a)&&(x6(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Kl=function(a,b,c,d){var e=u6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,x6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.R=function(){g.bs(this.l);v6.wa.R.call(this)};
g.h.Kz=function(a){u6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}x6(this,!b);b&&n6(this.F,"Missed "+b+" lounge tokens.")};
g.h.Jz=function(a){n6(this.F,"Requesting lounge tokens failed: "+a)};g.E(z6,g.R);g.h=z6.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.Xu("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?C6(this):(this.A=(0,g.G)()+3E5,g.Wu("yt-remote-fast-check-period",this.A),this.ip())};
g.h.isEmpty=function(){return g.dc(this.g)};
g.h.update=function(){y6("Updating availability on schedule.");var a=this.C(),b=g.Sb(this.g,function(b,d){return b&&!!M4(a,d)},this);
B6(this,b)};
g.h.R=function(){g.bs(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);z6.wa.R.call(this)};
g.h.ip=function(){g.bs(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=D6(this);if(g.Wb(a)){var b=h6(this.B,"/pairing/get_screen_availability");this.l=i6(this.B,b,{lounge_token:g.Yb(a).join(",")},(0,g.A)(this.LH,this,a),(0,g.A)(this.KH,this))}else B6(this,{}),C6(this)};
g.h.LH=function(a,b){this.l=null;var c=g.Yb(D6(this));if(g.kb(c,g.Yb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;B6(this,d);C6(this)}else this.Cb("Changing Screen set during request."),this.ip()};
g.h.KH=function(a){this.Cb("Screen availability failed: "+a);this.l=null;C6(this)};
g.h.Cb=function(a){n6("OnlineScreenService",a)};g.E(E6,r6);g.h=E6.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Kl=function(a,b,c,d){this.o.contains(a)?this.o.Kl(a,b,c,d):(a="Updating name of unknown screen: "+a.name,n6(this.F,a),d(Error(a)))};
g.h.rd=function(a){return a?this.g:g.Ya(this.g,(0,g.Ld)(this.A,function(a){return!this.contains(a)},this))};
g.h.wx=function(){return(0,g.Ld)(this.rd(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.xx=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new t6(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Le(f);d(F6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Le(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.cK=function(a,b,c,d){g.qs(h6(this.C,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,fb:(0,g.A)(function(a,d){var e=new E4(d.screen||{});if(!e.name||H6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);H6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(F6(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Xc:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.R=function(){g.Le(this.o);g.Le(this.l);E6.wa.R.call(this)};
g.h.Xz=function(){I6(this);this.P("screenChange");this.l.update()};
E6.prototype.dispose=E6.prototype.dispose;g.E(K6,g.R);g.h=K6.prototype;g.h.fl=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.td=function(a){this.ga()||(a&&L6(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){n6(this.O,a)};
g.h.zx=function(){return null};
g.h.qp=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){L6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.R=function(){this.qp("");K6.wa.R.call(this)};g.E(N6,K6);g.h=N6.prototype;g.h.pp=function(a){if(this.g){if(this.g==a)return;L6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);wja(this)};
g.h.th=function(a){this.info("launchWithParams no-op for Cast: "+g.xg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.td()},this),(0,g.A)(function(){this.td(Error("Failed to stop receiver app."))},this)):this.td(Error("Stopping cast device witout session."))};
g.h.qp=g.wa;g.h.R=function(){this.info("disposeInternal");g.bs(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;N6.wa.R.call(this)};
g.h.EI=function(a,b){if(!this.ga())if(b){var c=g.Kq(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.xg(c));switch(d){case "mdxSessionStatus":M6(this,c.screenId);break;default:L6(this,"Unknown youtube message: "+d)}}else L6(this,"Unable to parse message.")}else L6(this,"No data in message.")};
g.h.Cr=function(a,b,c,d){G6(this.I,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(L6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.$r((0,g.A)(this.Cr,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.zx=function(){return this.g};
g.h.dK=function(a){this.ga()||a||(L6(this,"Cast session died."),this.td())};g.E(O6,K6);g.h=O6.prototype;g.h.pp=function(a){this.A=a;this.A.addUpdateListener(this.L)};
g.h.th=function(a){this.B=a;this.F()};
g.h.stop=function(){this.g();this.g=g.wa;g.bs(this.C);this.A?this.A.stop((0,g.A)(this.td,this,null),(0,g.A)(this.td,this,"Failed to stop DIAL device.")):this.td()};
g.h.R=function(){this.g();this.g=g.wa;g.bs(this.C);this.A&&this.A.removeUpdateListener(this.L);this.A=null;O6.wa.R.call(this)};
g.h.gK=function(a){this.ga()||a||(L6(this,"DIAL session died."),this.g(),this.g=g.wa,this.td())};
g.h.qn=function(a){this.K=K4();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,Q6(this));a(b);P6(this)}else this.F=(0,g.A)(function(){g.bs(this.C);this.F=g.wa;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,Q6(this));a(b);P6(this)},this),this.C=g.$r((0,g.A)(function(){this.F()},this),100)};
g.h.tA=function(a,b,c){G6(this.I,this.H.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.fl(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.qn(b,c)},this),(0,g.A)(function(a){L6(this,"Failed to get DIAL screen: "+a);
this.qn(b,c)},this))};g.E(R6,K6);R6.prototype.stop=function(){this.td()};
R6.prototype.pp=g.wa;R6.prototype.th=function(){g.bs(this.g);this.g=window.NaN;var a=M4(this.I.rd(),this.l.label);a?this.fl(a):this.td(Error("No such screen"))};
R6.prototype.R=function(){g.bs(this.g);this.g=window.NaN;R6.wa.R.call(this)};g.E(S6,g.R);g.h=S6.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.hv,this),(0,g.A)(this.xH,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.JF,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ga()||(window.chrome.cast.addReceiverActionListener(this.A),nja(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.yx,this)),this.o=X6(this),window.chrome.cast.setCustomReceivers(this.o,g.wa,(0,g.A)(function(a){this.Cb("Failed to set initial custom receivers: "+g.xg(a))},this)),this.P("yt-remote-cast2-availability-change",V6(this)),b(!0))},this),(0,g.A)(function(a){this.Cb("Failed to initialize API: "+g.xg(a));
b(!1)},this))};
g.h.nJ=function(a,b){U6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)U6("Unsetting old screen status: "+this.g.l.friendlyName),W6(this,null)}if(a&&b){if(!this.g){c=M4(this.l.rd(),a);if(!c){U6("setConnectedScreenStatus: Unknown screen.");return}var d=T6(this,c);d||(U6("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.wa,(0,g.A)(function(a){this.Cb("Failed to set initial custom receivers: "+g.xg(a))},this)));
U6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);W6(this,new R6(this.l,d),!0)}this.g.qp(b)}else U6("setConnectedScreenStatus: no screen.")};
g.h.oJ=function(a){this.ga()?this.Cb("Setting connection data on disposed cast v2"):this.g?this.g.th(a):this.Cb("Setting connection data without a session")};
g.h.fK=function(){this.ga()?this.Cb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),W6(this,null)):U6("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.hv,this),(0,g.A)(this.PH,this))};
g.h.R=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.yx,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Wa(g.z("yt.mdx.remote.debug.handlers_")||[],j6);g.Le(this.g);S6.wa.R.call(this)};
g.h.Cb=function(a){n6("Controller",a)};
g.h.jv=function(a,b){this.g==a&&(b||W6(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.tH=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),U6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)U6("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{U6("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:W6(this,
new R6(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:W6(this,new O6(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:W6(this,new N6(this.l,a));break;default:this.Cb("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.Cb("Stopping receiver w/o session: "+a.friendlyName)}else this.Cb("onReceiverAction_ called without receiver.")};
g.h.JF=function(a){if(this.ga())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Cb("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.Cb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return U6("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Cb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);W6(this,new O6(this.l,b,this.C))}b=this.g;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.tA,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.qn,b))};
g.h.hv=function(a){if(!this.ga()){U6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)U6("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),W6(this,new N6(this.l,b),!0);else{this.Cb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=M4(this.l.rd(),c.label);
d&&F4(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(U6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Le(this.g),this.g=new N6(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.jv,this,this.g)),this.g.th(null));this.g.pp(a)}}};
g.h.eK=function(){return this.g?this.g.zx():null};
g.h.PH=function(a){this.ga()||(this.Cb("Failed to estabilish a session: "+g.xg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&W6(this,null))};
g.h.xH=function(a){U6("Receiver availability updated: "+a);if(!this.ga()){var b=V6(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;V6(this)!=b&&this.P("yt-remote-cast2-availability-change",V6(this))}};
g.h.yx=function(){this.ga()||(this.o=X6(this),U6("Updating custom receivers: "+g.xg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.wa,(0,g.A)(function(){this.Cb("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",V6(this)))};
S6.prototype.setLaunchParams=S6.prototype.oJ;S6.prototype.setConnectedScreenStatus=S6.prototype.nJ;S6.prototype.stopSession=S6.prototype.fK;S6.prototype.getCastSession=S6.prototype.eK;S6.prototype.requestSession=S6.prototype.requestSession;S6.prototype.init=S6.prototype.init;S6.prototype.dispose=S6.prototype.dispose;var f7=[];n7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";o7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.qe=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.I=a.duration,this.K=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
n7.prototype.isAdPlaying=function(){return 1081==this.g};
n7.prototype.clone=function(){return new n7(t7(this))};g.E(w7,g.R);g.h=w7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.wa,E7(this,"play")):C7(this,"play"),B7(this,1,r7(x7(this))),this.P("remotePlayerChange")):z7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.wa,E7(this,"pause")):C7(this,"pause"),B7(this,2,r7(x7(this))),this.P("remotePlayerChange")):z7(this,this.pause)};
g.h.tx=function(a){if(1==this.g){if(this.l){var b=x7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.g||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.wa,E7(this,"seekTo",{newTime:a}))}else C7(this,"seekTo",{newTime:a});B7(this,3,a);this.P("remotePlayerChange")}else z7(this,g.B(this.tx,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.wa,E7(this,"stopVideo")):C7(this,"stopVideo");var a=x7(this);a.index=-1;a.videoId="";o7(a);A7(this,a);this.P("remotePlayerChange")}else z7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=x7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){n6("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.Cb("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){n6("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.Cb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);C7(this,"setVolume",e)}c.muted=b;c.volume=a;A7(this,c)}else z7(this,g.B(this.setVolume,a,b))};
g.h.ow=function(a,b){if(1==this.g){var c=x7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.xg(b.style),g.kc(d,c.l));C7(this,"setSubtitlesTrack",d);A7(this,c)}else z7(this,g.B(this.ow,a,b))};
g.h.Np=function(a,b){if(1==this.g){C7(this,"setAudioTrack",{videoId:a,audioTrackId:b.ob.id});var c=x7(this);c.audioTrackId=b.ob.id;A7(this,c)}else z7(this,g.B(this.Np,a,b))};
g.h.rx=function(a,b){if(1==this.g){if(a&&b){var c=x7(this);s7(c,a,b);A7(this,c)}C7(this,"previous")}else z7(this,g.B(this.rx,a,b))};
g.h.qx=function(a,b){if(1==this.g){if(a&&b){var c=x7(this);s7(c,a,b);A7(this,c)}C7(this,"next")}else z7(this,g.B(this.qx,a,b))};
g.h.gr=function(){1==this.g?C7(this,"dismissAutoplay"):z7(this,this.gr)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}w7.wa.dispose.call(this)};
g.h.R=function(){y7(this);this.A=null;this.B.clear();v7(this,null);w7.wa.R.call(this)};
g.h.Op=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0==b.g.length&&(b.g=b.l,b.g.reverse(),b.l=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.qH=function(a,b){this.P(a,b)};
g.h.nF=function(a){if(!a)this.Ti(null),v7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=x7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)n6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,A7(this,b)}};
g.h.Ti=function(a){n6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.H);if(this.l=a)this.l.addUpdateListener(this.H),D7(this),this.P("remotePlayerChange")};
g.h.mF=function(a){a?(D7(this),this.P("remotePlayerChange")):this.Ti(null)};
g.h.AF=function(){var a=j7();a&&v7(this,a)};
g.h.Cb=function(a){n6("CP",a)};g.E(F7,g.R);g.h=F7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Ka.listId=c);this.Ka.videoId=d;this.Ka.index=k||0;this.Ka.state=3;q7(this.Ka,m);this.A="UNSUPPORTED";G7("Connecting with setPlaylist and params: "+g.xg(l));this.g.connect({method:"setPlaylist",params:g.xg(l)},a,S4())}else G7("Connecting without params"),
this.g.connect({},a,S4());Dja(this)};
g.h.dispose=function(){this.ga()||(this.P("beforeDispose"),H7(this,3));F7.wa.dispose.call(this)};
g.h.R=function(){I7(this);K7(this);J7(this);g.bs(this.I);this.I=window.NaN;g.bs(this.K);this.K=window.NaN;this.o=null;g.Gt(this.T);this.T.length=0;this.g.dispose();F7.wa.R.call(this);this.A=this.F=this.l=this.Ka=this.g=null};
g.h.Dz=function(){this.C(2)};
g.h.rF=function(){G7("Channel opened");this.U&&(this.U=!1,J7(this),this.O=g.$r((0,g.A)(function(){G7("Timing out waiting for a screen.");this.C(1)},this),15E3));
aja(lja(this.g),this.ba)};
g.h.oF=function(){G7("Channel closed");(0,window.isNaN)(this.B)?V4(!0):V4();this.dispose()};
g.h.pF=function(a){V4();(0,window.isNaN)(this.H())?(G7("Channel error: "+a+" without reconnection"),this.dispose()):(this.U=!0,G7("Channel error: "+a+" with reconnection in "+this.H()+" ms"),H7(this,2))};
g.h.qF=function(a){a.params?G7("Received: action="+a.action+", params="+g.xg(a.params)):G7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Kq(a.params.devices);this.l=(0,g.H)(a,function(a){return new D4(a)});
a=!!g.Na(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
N7(this,a);break;case "loungeScreenDisconnected":g.Xa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
N7(this,!1);break;case "remoteConnected":var b=new D4(g.Kq(a.params.device));g.Na(this.l,function(a){return b?a.id==b.id:!1})||g.Ua(this.l,b);
break;case "remoteDisconnected":b=new D4(g.Kq(a.params.device));g.Xa(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":O7(this,a);break;case "nowPlaying":Gja(this,a);break;case "onStateChange":P7(this,a);break;case "onAdStateChange":Hja(this,a);break;case "onVolumeChanged":Ija(this,a);break;case "onSubtitlesTrackChanged":Fja(this,a);break;case "nowAutoplaying":Jja(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.P("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":Kja(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:G7("Unrecognized action: "+a.action)}};
g.h.cJ=function(){if(this.o){var a=this.o;this.o=null;this.Ka.videoId!=a&&L7(this,"getNowPlaying")}};
F7.prototype.subscribe=F7.prototype.subscribe;F7.prototype.unsubscribeByKey=F7.prototype.Dc;F7.prototype.ha=function(){var a=3;this.ga()||(a=0,(0,window.isNaN)(this.H())?f6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
F7.prototype.getProxyState=F7.prototype.ha;F7.prototype.C=function(a){G7("Disconnecting with "+a);I7(this);this.P("beforeDisconnect",a);1==a&&V4();e6(this.g,a);this.dispose()};
F7.prototype.disconnect=F7.prototype.C;F7.prototype.da=function(){var a=this.Ka;this.o&&(a=this.Ka.clone(),s7(a,this.o,a.index));return t7(a)};
F7.prototype.getPlayerContextData=F7.prototype.da;
F7.prototype.sa=function(a){var b=new n7(a);b.videoId&&b.videoId!=this.Ka.videoId&&(this.o=b.videoId,g.bs(this.I),this.I=g.$r((0,g.A)(this.cJ,this),5E3));var c=[];this.Ka.listId==b.listId&&this.Ka.videoId==b.videoId&&this.Ka.index==b.index||c.push("remoteQueueChange");this.Ka.g==b.g&&this.Ka.volume==b.volume&&this.Ka.muted==b.muted&&r7(this.Ka)==r7(b)&&g.xg(this.Ka.l)==g.xg(b.l)||c.push("remotePlayerChange");this.Ka.reset(a);(0,g.F)(c,function(a){this.P(a)},this)};
F7.prototype.setPlayerContextData=F7.prototype.sa;F7.prototype.V=function(){var a=this.g.C.id,b=g.Na(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
F7.prototype.getOtherConnectedRemoteId=F7.prototype.V;F7.prototype.H=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
F7.prototype.getReconnectTimeout=F7.prototype.H;F7.prototype.X=function(){return this.A||"UNSUPPORTED"};
F7.prototype.getAutoplayMode=F7.prototype.X;F7.prototype.aa=function(){return this.F||""};
F7.prototype.getAutoplayVideoId=F7.prototype.aa;F7.prototype.ya=function(){if(!(0,window.isNaN)(this.H())){var a=this.g.l;g.Aq(a.g);a.start()}};
F7.prototype.reconnect=F7.prototype.ya;F7.prototype.ma=function(a,b){L7(this,a,b);M7(this)};
F7.prototype.sendMessage=F7.prototype.ma;g.E(Q7,r6);g.h=Q7.prototype;g.h.rd=function(a){return this.yc.$_gs(a)};
g.h.contains=function(a){return!!this.yc.$_c(a)};
g.h.get=function(a){return this.yc.$_g(a)};
g.h.start=function(){this.yc.$_st()};
g.h.add=function(a,b,c){this.yc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.yc.$_r(a,b,c)};
g.h.Kl=function(a,b,c,d){this.yc.$_un(a,b,c,d)};
g.h.R=function(){for(var a=0,b=this.l.length;a<b;++a)this.yc.$_ubk(this.l[a]);this.l.length=0;this.yc=null;Q7.wa.R.call(this)};
g.h.bK=function(){this.P("screenChange")};
g.h.XG=function(){this.P("onlineScreenChange")};
E6.prototype.$_st=E6.prototype.start;E6.prototype.$_gspc=E6.prototype.cK;E6.prototype.$_gsppc=E6.prototype.xx;E6.prototype.$_c=E6.prototype.contains;E6.prototype.$_g=E6.prototype.get;E6.prototype.$_a=E6.prototype.add;E6.prototype.$_un=E6.prototype.Kl;E6.prototype.$_r=E6.prototype.remove;E6.prototype.$_gs=E6.prototype.rd;E6.prototype.$_gos=E6.prototype.wx;E6.prototype.$_s=E6.prototype.subscribe;E6.prototype.$_ubk=E6.prototype.Dc;var R7=null,S7=null,h8=null,W7=[];g.r(k8,g.I);g.h=k8.prototype;
g.h.R=function(){g.I.prototype.R.call(this);this.A.stop();this.B.stop();this.L.stop();this.U();this.g.unsubscribe("proxyStateChange",this.fv,this);this.g.unsubscribe("remotePlayerChange",this.Ui,this);this.g.unsubscribe("remoteQueueChange",this.il,this);this.g.unsubscribe("autoplayUpNext",this.Gu,this);this.g.unsubscribe("previousNextChange",this.cv,this);this.g.unsubscribe("nowAutoplaying",this.Yu,this);this.g.unsubscribe("autoplayDismissed",this.Fu,this);this.g=this.H=null};
g.h.Kt=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(o8(this)){if(!x7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==x7(this.g).g?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.K.lh(c[0],c[1]);break;case "control_subtitles_set_track":p8(this,c[0]);break;case "control_set_audio_track":c=c[0],o8(this)&&this.g.Np(this.l.Y(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.xa();q8(this,0==c?void 0:c);break;case "control_seek":q8(this,c[0]);break;case "control_subtitles_set_track":p8(this,c[0]);break;case "control_set_audio_track":c=c[0],o8(this)&&this.g.Np(this.l.Y(1).videoId,c)}};
g.h.lF=function(a){this.L.Az(a)};
g.h.IJ=function(a){this.Kt("control_subtitles_set_track",g.dc(a)?null:a)};
g.h.Bw=function(){var a=this.l.Ob("captions","track");g.dc(a)||p8(this,a)};
g.h.Wu=function(a){if(o8(this)){this.g.unsubscribe("remotePlayerChange",this.Ui,this);var b=Math.round(a.volume);a=!!a.muted;var c=x7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.O.start();this.g.subscribe("remotePlayerChange",this.Ui,this)}};
g.h.qG=function(){g.dc(this.C)||r8(this,this.C);this.F=!1};
g.h.fv=function(a,b){this.B.stop();2==b&&this.yw()};
g.h.Ui=function(){if(o8(this)){this.A.stop();var a=x7(this.g);switch(a.g){case 1081:case 1:m8(this,new g.mE(8));this.xw();break;case 1085:case 3:m8(this,new g.mE(9));break;case 1083:case 0:m8(this,new g.mE(2));this.K.stop();l8(this,this.l.Y().lengthSeconds);break;case 1084:m8(this,new g.mE(4));break;case 2:m8(this,new g.mE(4));l8(this,r7(a));break;case -1:m8(this,new g.mE(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.S("YTP_MDX_PLAYER_ERROR")},m8(this,new g.mE(128,a))}a=x7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,r8(this,a));a=x7(this.g);-1==a.volume||Math.round(this.l.Nb())==a.volume&&this.l.isMuted()==a.muted||this.O.isActive()||this.gx()}else n8(this)};
g.h.cv=function(){this.l.P("mdxpreviousnextchange")};
g.h.il=function(){o8(this)||n8(this)};
g.h.Yy=function(){this.g.gr()};
g.h.Gu=function(a){a&&(a=g.qs("/watch_queue_ajax",{method:"GET",Ec:{action_get_watch_queue_item:1,video_id:a},fb:(0,g.A)(this.nI,this)}))&&(this.U=(0,g.A)(a.abort,a))};
g.h.nI=function(a,b){var c=new g.mD({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.Yu=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.Fu=function(){this.l.P("mdxautoplaycanceled")};
g.h.kD=function(a,b){-1==x7(this.g).g?q8(this,a):b&&this.g.tx(a)};
g.h.gx=function(){if(o8(this)){var a=x7(this.g);this.o.Qa(this.T);a.muted?this.l.mute():this.l.Ce();this.l.setVolume(a.volume);this.T=this.o.M(this.l,"onVolumeChange",this.Wu)}};
g.h.xw=function(){this.A.stop();if(!this.g.ga()){var a=x7(this.g);1==a.g&&m8(this,new g.mE(8));l8(this,r7(a));this.A.start()}};
g.h.yw=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.r(u8,g.U);u8.prototype.o=function(a){t8(this,a.state)};g.r(v8,g.oT);v8.prototype.I=function(){var a=this.g.Ob("remote","receivers");a&&1<a.length&&!this.g.Ob("remote","quickCast")?(this.F=g.lb(a,this.A,this),g.pT(this,(0,g.H)(a,this.A)),a=this.g.Ob("remote","currentReceiver"),this.be(this.A(a)),this.enable(!0)):this.enable(!1)};
v8.prototype.A=function(a){return a.key};
v8.prototype.ae=function(a){return"cast-selector-receiver"==a?g.S("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
v8.prototype.Jc=function(a){g.oT.prototype.Jc.call(this,a);this.g.Wc("remote","currentReceiver",this.F[a]);this.o.qb()};g.r(w8,g.dL);g.h=w8.prototype;g.h.create=function(){Pja(g.JB(g.W(this.g)));this.C.push(g.hu("yt-remote-before-disconnect",this.iF,this));this.C.push(g.hu("yt-remote-connection-change",this.yH,this));this.C.push(g.hu("yt-remote-receiver-availability-change",this.dv,this));this.C.push(g.hu("yt-remote-auto-connect",this.wH,this));this.C.push(g.hu("yt-remote-receiver-resumed",this.vH,this));this.dv()};
g.h.load=function(){this.g.jo();g.dL.prototype.load.call(this);this.B=new k8(this,this.g,this.l);var a=(a=j8())?a.currentTime:0;var b=g8()?new w7(b8(),void 0):null;0==a&&b&&(a=r7(x7(b)));0!=a&&(this.F=a||0,this.g.P("progresssync",a,void 0));s8(this,this.H,this.H);g.JV(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.Me(this.B,this.l);this.l=this.B=null;g.dL.prototype.unload.call(this);g.JV(this.g.app,5)};
g.h.R=function(){g.iu(this.C);g.dL.prototype.R.call(this)};
g.h.Ki=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.Kt.apply(this.B,[].concat([a],g.pa(c)))};
g.h.xz=function(){return this.loaded?this.B.suggestion:null};
g.h.qe=function(){return this.l?x7(this.l).qe:!1};
g.h.hasNext=function(){return this.l?x7(this.l).hasNext:!1};
g.h.aD=function(){var a=x7(this.l),b=this.g.Y();return{allowSeeking:this.g.Ac(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.F,displayedStart:-1,duration:a.C?a.I+p7(a):a.I,ingestionTime:a.C?a.A+p7(a):a.A,isPeggedToLive:1>=(a.C?a.o+p7(a):a.o)-this.F,loaded:a.K,seekableEnd:a.C?a.o+p7(a):a.o,seekableStart:0<a.B?a.B+p7(a):a.B}};
g.h.bD=function(){this.l&&this.l.qx()};
g.h.cD=function(){this.l&&this.l.rx()};
g.h.iF=function(a){1==a&&(this.K=this.l?x7(this.l):null)};
g.h.yH=function(){var a=g8()?new w7(b8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.K=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Le(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.Y().videoId&&this.g.ht(a.videoId,r7(a)));this.g.P("videodatachange","newdata",this.g.Y(),3)};
g.h.dv=function(){this.I=[this.o].concat(Qja());var a=c8()||this.o;x8(this,a);this.g.ka("onMdxReceiversChange")};
g.h.wH=function(){var a=c8();x8(this,a)};
g.h.vH=function(){this.A=c8()};
g.h.ZC=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.I;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l7():x8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.I.length&&"cast-selector-receiver"==this.I[1].key?(b&&l7(),!0):!1}};
g.h.dD=function(){C7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.sc=function(){return!1};g.IQ.remote=w8;})(_yt_player);
